version: "3"

volumes:
  whatsapp-session:
  media:

services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    networks:
      - network
    env_file:
      - ./bot/.env
    volumes:
      - whatsapp-session:/.wwebjs_auth/session
      - ./bot/src:/src
      - ./bot/node_modules:/node_modules
      - media:/media
    command: npm run start
    restart: unless-stopped
    depends_on:
      - browser

  browser:
    image: browserless/chrome:latest
    hostname: browser
    volumes:
      - whatsapp-session:/usr/src/app/user-data-dir
    environment:
      CONNECTION_TIMEOUT: -1
      DEFAULT_USER_DATA_DIR: /usr/src/app/user-data-dir
    ports:
      - 3000:3000
    networks:
      - network

  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    env_file:
      - ./web/.env
    ports:
      - 4001:80
    restart: always
    volumes:
      - ./web/config:/app/config
      - ./web/database:/app/database
      - ./web/public:/app/public
      - ./web/app:/app/app
      - ./web/resources:/app/resources
      - ./web/routes:/app/routes
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "./web/docker:/app/docker"
      - media:/app/public/media
    networks:
      - network


networks:
  network:
    external:
      name: arbit

