version: "3"

volumes:
  whatsapp-session:
  media:

services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    networks:
      - network
    environment:
      BROWSER_URL: 'ws://browser:3000'
    volumes:
      - whatsapp-session:/.wwebjs_auth/session
      - media:/media
    command: npm run start
    restart: unless-stopped
    depends_on:
      - browser

  browser:
    image: browserless/chrome:latest
    hostname: browser
    volumes:
      - whatsapp-session:/usr/src/app/user-data-dir
    environment:
      CONNECTION_TIMEOUT: -1
      KEEP_ALIVE: 'true'
      WORKSPACE_EXPIRE_DAYS: 1
      ENABLE_CORS: 'true'
      CHROME_REFRESH_TIME: 86400000
      DEFAULT_BLOCK_ADS: 'true'
      FUNCTION_ENABLE_INCOGNITO_MODE: 'true'
      ENABLE_XVBF: 'true'
      CHROME_PATH: '/usr/bin/google-chrome'
      USE_CHROME_STABLE: 'true'
      NODE_ENV: 'production'
      MAX_CONCURRENT_SESSIONS: 1
      DEFAULT_USER_DATA_DIR: /usr/src/app/user-data-dir
    ports:
      - 3000:3000
    networks:
      - network

  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    env_file:
      - ./web/.env
    ports:
      - 4001:80
    restart: always
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - media:/public/media
    networks:
      - network



networks:
  network:
    external:
      name: arbit
